### ISSUE TITLE
When using mock mode, fog file cannot be read

### ISSUE THREAD

**Issue by phuongnd08** [fog/fog#1043]
I use carrier wave + fog to upload file to s3.
So I enable mock mode of fog for testing.
Problem is, I do some post processing over the uploaded file, so I re-read the file by calling:
my_model.avatar.read

Then I receive: Undefined body of nil.

Look like under mock mode, the fog.directories.head(fog_path) return a nil object even when it should not, thus cause the file to not be able to read.

**Comment by zdennis** [comment]
For testing processing rules you can use a `before/after` (RSpec) to set the storage to `:file` in before and then to reset it in after. E.g.

```ruby
before do
  AttachmentUploader.storage :file
end

after do
  AttachmentUploader.storage Rails.application.config.carrierwave_storage
end
```

**Comment by mltsy** [comment]
Oddly (because this is such an old issue) I'm having the same problem using fog-core 2.1 - and I guess... I should say I *had* the same problem a couple times, and I can't get it to appear again, but now instead of that error, I'm just getting a blank string back from `model.attachment.read`.

It's a very finicky bug... I'm running into it in a repo where the tests have been running fine for a while, and I just switched laptops to one running PopOS (Ubuntu remix) natively, where this started happening... I'm sure other things about my configuration have changed slightly, but the tests still pass in CI (which is running in docker on Google Cloud Build), and pass on my old laptop, but fail on my new laptop (also running the tests in docker using the same image).

The other interesting part in my use-case is that the error only occurs when I load a `Rack::Test::UploadedFile` into the uploader.  If I replace that with a plain old `File.new` it works fine.  The `Rack::Test::UploadedFile` is supposed to simulate an uploaded file, which is why we had that in the tests previously, but there's really no reason to use that in this case, so I'm just replacing it with `File.new` since it works.

Hoping this can provide at least a little helpful insight...

**Comment by geemus** [comment]
@mitsy Thanks for sharing your context and findings, it doesn't immediately put further fixes in mind for me, but I definitely appreciated having more data points to help think about what might be going on.
