### ISSUE TITLE
Clearer service definitions and specs

### ISSUE THREAD

**Issue by tokengeek** [fog/fog#1252]
In discussing a rough roadmap (#1250) for Fog everyone is keen for us to work on getting clearer definitions of the Fog services that providers should be implementing.

Even some of the services are muddled. Load balancers is available on several providers but you can't just use `LoadBalancer[:provider]` to gain access to the service as you can with `Compute` services.

So this issue is to discuss what we can do to get back on track.

Services that look "official" are:
- CDN
- Compute
- DNS
- Storage

Ad-hoc services include:
- Load balancers (defined by Rackspace, `ELB` branded version for AWS and part of Compute's models in Brightbox)

@nirvdrum wanted to audit some of the higher level stuff. Others are welcome to chime in as well.

@ahmeij mentioned us looking at moving provider specific parts to being non standard extensions (clearly marked as such). Also the possible need for an additional level besides models and requests to wrap provider specific models in these standardised versions.

The other part of this is that the interface we define needs to be specified by tests that providers can include and run to ensure they meet the requirements. The tests that currently do this need work.

I think we can discuss general ideas here and then break each service down as further issues to decide exactly what a standard Fog service should be capable of.

**Comment by ihmccreery** [comment]
@tokengeek is this issue still relevant?  I see you added significant new functionality to Services between the last comment and now.  I also see this issue has the `summit` label: can you or someone else please update on where this stands post-summit?

**Comment by ihmccreery** [comment]
@tokengeek Based on [the Roadmap](https://github.com/fog/fog/wiki/Roadmap) in the Wiki, this looks like it should be marked as a v2.x issue?

**Comment by tokengeek** [comment]
Honestly I don't think we've done much about this!

Basically for the mentioned services, we should have a module similar to https://github.com/fog/fog-core/blob/9223a708df00be856c1413ac8970f3426509e106/lib/fog/core/service_abstraction_spec.rb that each provider can include in their own tests.

As more behaviour is agree upon, these tests will start bringing these definitions in-line.

Re: `summit` - I think the majority of discussion was positive and most of the changes were agree upon including this.

The problem was after the summit, everyone who attended seemed to have changes in circumstances. Several job changes, responsibility changes and the like.

We're probably going to start on v2 this Friday, following tomorrow's release. We've decided to narrow down each major change so to to not overwhelm (users and us). So that will probably just cover what's on the milestone at the moment.

If we add these specs then I'm not sure how many required changes are going to be highlighted. If it's not much then this could become a 2.0 thing but we've not assessed it yet.

**Comment by ihmccreery** [comment]
@tokengeek thanks for the clarification.  A lot of what you wrote here could probably end up informing the design document referenced in #3508.

**Comment by hedgehog** [comment]
after some time away from fog I'm likely returning..... Issue #1266 is closed. It was correct I spent time on other lib contributions (mainly the "ssh hangs"  issue in Vagrant) rather than learn Shindo.  

Nice that Fog appears to leave the door open to vendor gems adopting a test/spec library other than minitest.  Is that still a correct understanding?
I don't want to get into an argument, but people should understand that stearing clear of minitest is a rational choice when you have alternative uses for your time.  Why? This [Minitest issue](hanging) was determinative for me.  
For anyone I lead/mentor, I emphasis to them that the best investment of their time is to learn another language rather than learn another library, choose (carefully) a library in Ruby and stick with it, developing it where it falls down is a better use of your time that learning another library.
As that Minitest issue makes clear Minitest is a terrible thing to choose to invest your time in. 
Any library that thinks its okay to beak core behavior, and rejects a patch/suggestion without saying where it is defective, is a poor investment of my team member's time.  I don't stop them but I do warn them.

Sooooo..... is Fog still open to not-mintest tested contributions?  A Yes/No response is perfect. I don't expect more than that - we all have other things we can be doing ;)

**Comment by geemus** [comment]
@hedgehog hey, yeah we expect on the non-core gems that people should adopt whatever makes the most sense for them. So there is already a bit of variation, though some just never ported away from where things started. I agree that there are some challenging things in the way minitest is maintained which give me some pause as well.

**Comment by hedgehog** [comment]
@geemus thanks for taking the time to respond.

**Comment by ioquatix** [comment]
@hedgehog As the author of that PR, I appreciate what you've said. It was really frustrating for me too, since it's such an obvious fix. I just don't get how someone who could make something as complicated as minitest could be so uninterested in making it better. It seems like such a toxic way to run a project. I certainly couldn't be bothered investing further time into it. I'd rather focus my efforts towards more positive outcomes.
