### ISSUE TITLE
Support for Proxmox VE

### ISSUE THREAD

**Issue by pfa230** [fog/fog#1328]
Proxmox is quite popular platform for in-house virtualised environments (http://pve.proxmox.com/pve2-api-doc/). Are there any plans supporting it?

If "not yet" - would it be interesting if I'll work on it?

**Comment by mrjcleaver** [comment]
Per https://github.com/fog/fog/issues/3405 - OpenVZ is supported in fog.io, it just wasn't documented. (https://github.com/fog/fog.github.com/issues/32)

Proxmox provides an OpenVZ environment. A lot of fog.io access will suffice through the OpenVZ API.

**Comment by numkem** [comment]
@mrjcleaver - you mention OpenVZ but not KVM, is support only planned for Proxmox through the OpenVZ API and not KVM?

**Comment by mrjcleaver** [comment]
Hi @numkem - to my knowledge the only reason Proxmox is supported (and I have not tested it) is because there already is OpenVZ support in Fog. 

Proxmox has two sets of APIs, the other being KVM. I don't use KVM so I haven't looked whether Fog could support it.

This said, I was very surprised that OpenVZ had Fog support. @jedi4ever built that a long while back but it simply didn't get put it in the documentation. 

It is therefore conceivable that someone has built a KVM driver but not documented it.

**Comment by pschichtel** [comment]
I'm interested as well and I might have some time in the coming months to work on this

**Comment by mrjcleaver** [comment]
Are you interested in KVM or OpenVZ support for Proxmox, @pschichtel ?

**Comment by pschichtel** [comment]
@mrjcleaver I'm interested in KVM and LXC once PVE 4 is stable as we're using the 3.X kernel with PVE that doesn't support OpenVZ

**Comment by caffecoder** [comment]
I'm interested the same things as @pschichtel

**Comment by MACscr** [comment]
I would really love support for proxmox4 as well.

**Comment by plribeiro3000** [comment]
@MACscr Take a look at #3644 . That issue is centralized for all provider requests.

**Comment by mrjcleaver** [comment]
Take a look at https://github.com/telcat/vagrant-proxmox/issues/25#issuecomment-159269708

**Comment by gittygoo** [comment]
Please support this :)

**Comment by plribeiro3000** [comment]
@gittygoo Take a look at #3644.
