### ISSUE TITLE
AWS SQS AddPermission API missing

### ISSUE THREAD

**Issue by rcrocker** [fog/fog#3375]
Pretty straightforward: the AddPermission API from AWS SQS (http://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_AddPermission.html) is not available in Fog::AWS::SQS.

Is this intentional (i.e., there's some issue with it) or inadvertent? If the latter, please add.

(EDIT: RemovePermission is also missing... might as well add that one too)

**Comment by geemus** [comment]
It is (to the best of my knowledge) inadvertent. We usually add things as people need them, so perhaps nobody happened to need that yet. I'd certainly welcome a pull request with this addition, otherwise it might be a bit before somebody is able to tackle this. Just let me know if you have questions or anything I can help with. Thanks!

**Comment by plribeiro3000** [comment]
Closed in favor of fog/fog-aws#26
