### ISSUE TITLE
[vsphere] rbvmomi is not listed as a dependency

### ISSUE THREAD

**Issue by Fryguy** [fog/fog#3465]
It is listed as a development dependency in the gemspec, but not a runtime dependency.  How can vsphere actually work without it?  I tried look for documentation somewhere that states you have to install it manually before using vsphere, but I don't know where to even look.  Should this be documented somewhere if it is, in fact, a manual dependency?

**Comment by geemus** [comment]
It is presently a manual require, because a lot of people who use fog don't necessarily use vsphere. Ideally at some point we'll split out fog-vsphere to it's own gem (at which point it becomes much more tenable to have this require additional gems as needed). In the mean time, documenting would be great, any thoughts on where we should put it to make it super clear? Maybe we could rescue load errors here and notify you that you will need to manually require (if nothing else). Thanks!

**Comment by plribeiro3000** [comment]
Vsphere was already extracted as [`fog-vsphere`](https://github.com/fog/fog-vsphere).
Any extra need of documentation can be worked on the new repo.

Thanks for your help on improving this @Fryguy
