### ISSUE TITLE
[vsphere] The clone_vm method fails to create a linked clone.

### ISSUE THREAD

**Issue by pdilung** [fog/fog#3480]
The `clone_vm` method fails to clone from a template when `linked_clone` option is set to `true`:
```
/home/pdilung/.gem/ruby/1.9.1/gems/rbvmomi-1.8.2/lib/rbvmomi/vim/Task.rb:11:in `wait_for_completion': NotSupported: Der Vorgang wird für dieses Objekt nicht unterstützt. (RbVmomi::Fault)
        from /home/pdilung/.gem/ruby/1.9.1/bundler/gems/fog-be1bb990d6bf/lib/fog/vsphere/requests/compute/vm_clone.rb:232:in `block in vm_clone'
        from /home/pdilung/.gem/ruby/1.9.1/bundler/gems/fog-be1bb990d6bf/lib/fog/vsphere/requests/compute/vm_clone.rb:214:in `each'
        from /home/pdilung/.gem/ruby/1.9.1/bundler/gems/fog-be1bb990d6bf/lib/fog/vsphere/requests/compute/vm_clone.rb:214:in `vm_clone'
        from /home/pdilung/dopv/lib/dopv/infrastructure/providers/vsphere.rb:125:in `create_vm'
        from /home/pdilung/dopv/lib/dopv/infrastructure/providers/vsphere.rb:46:in `initialize'
        from /home/pdilung/dopv/lib/dopv/infrastructure/base_node.rb:5:in `new'
        from /home/pdilung/dopv/lib/dopv/infrastructure/base_node.rb:5:in `bootstrap'
        from /home/pdilung/dopv/lib/dopv/infrastructure/core.rb:65:in `bootstrap'
        from /home/pdilung/dopv/lib/dopv/plan.rb:68:in `block in execute'
        from /home/pdilung/dopv/lib/dopv/plan.rb:68:in `each'
        from /home/pdilung/dopv/lib/dopv/plan.rb:68:in `execute'
        from bin/dopv:75:in `<main>'
```
_Der Vorgang wird für dieses Objekt nicht unterstützt_ could be translated into English as: _The operation is not supported for this object_.

I would really need to create thin provisioned clones from a template. Is it possible to achieve this in a different way?

**Comment by geemus** [comment]
@nirvdrum could you look when you get a chance? Thanks!

**Comment by nirvdrum** [comment]
@pdilung Sorry for just getting around to this.  But linked clones need to made from a snapshot of the parent, as I understand it.  Since templates don't have snapshots, that wouldn't be doable.  The only way I can really see solving that is to clone from the template, take a snapshot, and take a linked clone from that.

If you're just looking do thin provisioned clones from a template, I don't think you need linked clones at all.  I believe the clone will inherit whatever provisioning type the template has.  I just cloned a VM and had a thin provisioned root store.  This is on vSphere 5.5 (I think behavior might have been different on 5.0 -- it might always provision thick & lazy but I haven't run that in a year and can't quite recall).  Of course, a thin provisioned clone of a template is different than a linked clone as there's no disk sharing.

**Comment by geemus** [comment]
Thanks!

**Comment by nirvdrum** [comment]
I'm not sure if there's really any action to take on this, so I'm optimistically closing it out.  @pdilung Please comment if you think there's still something for us to do here.
