### ISSUE TITLE
Kubernetes on Fog?

### ISSUE THREAD

**Issue by ihmccreery** [fog/fog#3512]
The [Kubernetes](http://kubernetes.io/) team has expressed interest in building Kubernetes support into Fog.  Kubernetes is a system for managing containerized applications across multiple hosts, providing basic mechanisms for deployment, maintenance, and scaling of applications.  Although concepts in Kubernetes don't necessarily map exactly to what Fog is often used for, (Kubernetes deals with pods of containters rather than machines/servers).  More information in the [Kubernetes Design Overview](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/DESIGN.md).

Would the Fog community be interested in supporting Kubernetes?  The Kubernetes team would happily contribute resources to make it happen if we decide it would be a good fit.

**Comment by icco** [comment]
I don't understand, what would fog do for kubernetes?

**Comment by plribeiro3000** [comment]
Is this something that relates to `google` only?

If yes i think it is up to you guys that are ahead of `fog-google` to decide since it will be on your homeland. =)

For me its a yes because it the quantity of providers support by fog is that make me love it. =)

**Comment by ihmccreery** [comment]
@icco I think the team is imagining that one could use fog to provision resources on—or maybe even initially start up—a Kubernetes cluster, acting as a replacement for `kubectl` ([docs](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/kubectl.md)) within the Ruby ecosystem.  Whether or not that's useful or reasonable, or if there are other designs to consider, should be discussed here.

@plribeiro3000 No, this is not something that relates to `google` only, since Kubernetes is [a multi-platform solution](https://github.com/GoogleCloudPlatform/kubernetes/tree/master/docs/getting-started-guides), (though it should be noted that initial development was done on GCE and so the instructions and scripts are built around that.

**Comment by tokengeek** [comment]
I was sounded out on Twitter about adding support.

I'm fine with the idea if we can find the correct service for it. I'm not sure if it fits more into orchestration rather than say compute.

`rkt` (aka Rocket) has introduced pod support so perhaps there is some possible service there for "containers" or "pods" that Kubernetes can provide or rkt can provide locally.

We have Docker as a compute provider but if "pods" better fit then we should be look at specifying that interface somehow.

Just some ideas there.

**Comment by icco** [comment]
Ah. Is there a link to the public docs that fog would wrap around? Probably trying to define a common pod structure would be a decent integration point.

I very much hate creating new integrations that are service specific, so if we can come up with a common (aka multiple providers) use case, then sure. Otherwise I don't see why it should go in fog and shouldn't just be a ruby wraper for the kubernetes API.

**Comment by tokengeek** [comment]
The "pods" as rkt implements is part of the ACI spec... https://github.com/appc/spec/blob/master/SPEC.md#app-container-pods-pods

Whether these are the same kind of things or directly mappable I'm not sure.

I used `rkt` as an example but a few hours later I realise we're unlikely to be shelling out to a golang implementation from `fog`. So a second implementation of a "pod" service might be a while since we're probably waiting for a pure Ruby implementation to be done OR a wrapper around the C++ `libappc`

**Comment by eLobato** [comment]
As an user & contributor to the FogDocker provider for some time, the biggest advantage that Fog provides which is an abstraction over VM providers, is practically lost with containers. The reason being that common methods such as `.vms`, `.create_vm`, `.image` etc... stop making sense that much in containers, not only syntactically (I can live with calling .vms to get containers and calling .image to get a container repository+tag). What abstractions from [fog-core](https://github.com/fog/fog-core) do you plan to use? I think that's a good rule of thumb to check if the project would fit as a provider or not.

I'd say alternatives similar to what @abonas started here https://github.com/abonas/kubeclient , are better suited for handling clusters of containers rather than fog, so big :-1: to this (and big :+1:  to make it a separate project, I'd definitely use it!).

**Comment by abonas** [comment]
> As an user & contributor to the FogDocker provider for some time, the biggest advantage that Fog provides which is an abstraction over VM providers, is practically lost with containers. The reason being that common methods such as .vms, .create_vm, .image etc... stop making sense that much in containers, not only syntactically (I can live with calling .vms to get containers and calling .image to get a container repository+tag). What abstractions from fog-core do you plan to use? I think that's a good rule of thumb to check if the project would fit as a provider or not.
> 
> I'd say alternatives similar to what @abonas started here https://github.com/abonas/kubeclient , are better suited for handling clusters of containers rather than fog, so big :-1: to this (and big :+1: to make it a separate project, I'd definitely use it!).

@eLobato, 
I evaluated at the beginning of [kubeclient](https://github.com/abonas/kubeclient ) development whether to add it to Fog, and similarly to you decided that it's better suited as a standalone project.

@ihmccreery , 
Google team are aware of  [kubeclient](https://github.com/abonas/kubeclient ), and it's actually listed on the [clients page](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/client-libraries.md)

**Comment by ihmccreery** [comment]
Okay, thanks to everyone for your feedback; I'm going to go ahead and close this issue.  I really appreciate you all taking the time to hash this out.
