### ISSUE TITLE
I can't seem to find the appropriate request to list Hosts objects 

### ISSUE THREAD

**Issue by bechampion** [fog/fog#3534]
Hi List.
Is there any way to list ESXi Hosts?? i Can't seem to find it anywhere in the code.

Thanks!

**Comment by plribeiro3000** [comment]
Hello @bechampion. Those ESXi hots are related to which provider?

**Comment by bechampion** [comment]
HI there ,  Vpshere would be .
Thans!

**Comment by geemus** [comment]
@nirvdrum could you maybe chime in when you get a moment? Thanks!

**Comment by nirvdrum** [comment]
Sorry, I didn't realize this was a support question.  In any event, I just looked and it seems you can get the host information from the clusters, which belong to a datacenter.

In a simple two host cluster, I have the following:

```
compute_provider.datacenters.first.clusters
=>   <Fog::Compute::Vsphere::Clusters
    [
                  <Fog::Compute::Vsphere::Cluster
        id="domain-s17",
        name="10.10.50.3",
        datacenter="Rochdale",
        num_host=1,
        num_cpu_cores=8,
        overall_status="gray",
        full_path="10.10.50.3"
      >, 
                  <Fog::Compute::Vsphere::Cluster
        id="domain-s7",
        name="10.10.50.2",
        datacenter="Rochdale",
        num_host=1,
        num_cpu_cores=8,
        overall_status="gray",
        full_path="10.10.50.2"
      >    
    ]
  >
```

If you're looking for more than that, I'm afraid you'll have to drop to the service level and issue requests directly.  Since we route everything through rbvmomi, you'd have to work out what their API does (it closely mirrors the structure of the vSphere API).

**Comment by geemus** [comment]
Thanks!
