### ISSUE TITLE
[cloudstack] API does not provide a way to pass the hypervisor type to cloudstack

### ISSUE THREAD

**Issue by dra** [fog/fog#3588]
Hi everybody.

I am currently working on the CloudStack plugin for Foreman (https://github.com/bytemine/foreman_cpp_cloudstack) and struggling to hand over the hypervisor type for ISO deployments to CloudStack.
Am I missing anything, or is this currently not implemented?

Thanks alot, Daniel

**Comment by dra** [comment]
No response? Am I the only one that would use this feature?
Daniel

**Comment by geemus** [comment]
I haven't used cloudstack I fear.

@athirn @fifthecho either of you able to provide more insight? Thanks!

**Comment by athirn** [comment]
the service provider I have been using has switched to openstack so I'm unable to work on Cloudstack anymore.  sorry

**Comment by geemus** [comment]
@athirn no problem, thanks for the update.

**Comment by fifthecho** [comment]
@dra According to the https://cloudstack.apache.org/api/apidocs-4.5/user/deployVirtualMachine.html documentation, you should be able to use https://github.com/fog/fog/blob/master/lib/fog/cloudstack/requests/compute/deploy_virtual_machine.rb by building all the options into a hash (hypervisor, serviceoffering, zone, template [which would be the ISO ID], ROOT disk offering, and network or security group) and passing that hash of values into the deployVirtualMachine call.

This weekend I should be able to get my home ACS lab back up and running and give you an explicit example.

**Comment by dra** [comment]
Sorry, I am pretty stuck here, as foreman does not call deploy_virtual_machine directly. My call stack looks basically like this:
module ForemanCPPCloudstack
  class Cloudstack < ComputeResource
  def create_vm
    ...
    client.servers.create options (client.server.class = Fog::Compute::Cloudstack::Servers)
  end
end

This seems to end up in lib/fog/cloudstack/models/compute/server.rb in save() where the options hash is defined with fixed keys. So I see no way on how to pass the hypervisor option to fog.

Any help is really appreciated.
Bye, Daniel

**Comment by fifthecho** [comment]
Okay, that's a method which, to be honest, I'd never really started using until recently when I've started working on chef-provisioning-fog for CloudStack support and discovered it's using the same mechanism to use Fog.

It may take me a bit of time to refactor this model and not break historical usage of this model but be able to better support all of the options available from CloudStack.

**Comment by dra** [comment]
Hi Jeff.
Are there any news on this. How can I help?
Bye, Daniel

**Comment by fifthecho** [comment]
Daniel,
My apologies on the delays, but I've had a rather catastrophic failure of parts of my development and test environment which (hopefully) should all be fixed in the next 2-3 weeks.
The bigger issue (and possibly where you can help in the interim) is that the current tests don't pass for any of the CloudStack code. Before refactoring such a core model, we need to get passing tests in place and that's where I'm going to start once I get the development environment (which should be working again early next week) and once we have functional tests, then we can refactor to extend the model to support these additional options and calls.
Once the model is refactored and I have my test environment back up, then I can validate code and push the changes.

So there's several things on the agenda for this issue:
1) Rebuild tests for CloudStack so that current code is passing tests
2) Extend mocks to support additional API calls (preferably using a functioning CloudStack environment to have real-world based output)
3) Refactor Server model to pass existing tests but support additional API functionality
4) Extend tests while refactoring
5) Validate against functioning CloudStack environment
6) Push change

**Comment by dra** [comment]
Hi Jeff. How is the refactoring going? It is quite hard to keep track with all the commits and find out about the state of this issue.
Thanks for your information, Daniel

**Comment by dra** [comment]
Hi.
Is there anybody who can tell me the status on this refactoring? Is there any chance I can procede my work, or is this whole refactoring thing stucked?
Thanks alot!
Daniel

**Comment by fifthecho** [comment]
I am still working on this. I apologize that it's slow going, but I'm making progress on getting the tests in place to then get the refactoring done.
