### ISSUE TITLE
fog Truck Factor

### ISSUE THREAD

**Issue by gavelino** [fog/fog#3654]
As part of my PhD research on code authorship, we calculated the Truck Factor (TF) of some popular GitHub repositories.

As you probably know, the [Truck (or Bus) Factor](https://en.wikipedia.org/wiki/Bus_factor) designates the minimal number of developers that have to be hit by a truck (or quit) before a project is incapacitated. In our work, we consider that a system is in trouble if more than 50% of its files become orphan (i.e., without a main author).

More details on our work in this preprint: https://peerj.com/preprints/1233

We calculated the TF for **fog** and obtained a value of **12**.

The developers responsible for this TF are:

Paul Thornthwaite - author of 24% of the files
Matt Darby - author of 14% of the files
Jeff Moody - author of 12% of the files
Rupak Ganguly - author of 9% of the files
Wesley Beary (geemus) - author of 9% of the files
Sergio Rubio - author of 5% of the files
Ferran Rodenas - author of 5% of the files
Nick Osborn - author of 5% of the files
Kyle Rames - author of 4% of the files
Brian Hartsock - author of 3% of the files
Brad Gignac - author of 3% of the files
Lincoln Stoll - author of 3% of the files

To validate our results, we would like to ask **fog** developers the following three brief questions:

(a) Do you agree that the listed developers are the main developers of **fog**?

(b) Do you agree that **fog** will be in trouble if the listed developers leave the project (e.g., if they win in the lottery, to be less morbid)?

(c) Does **fog** have some characteristics that would attenuate the loss of the listed developers (e.g., detailed documentation)?

Thanks in advance for your collaboration,

Guilherme Avelino
PhD Student
Applied Software Engineering Group (ASERG)
UFMG, Brazil
http://aserg.labsoft.dcc.ufmg.br/

**Comment by TerryHowe** [comment]
Well, Rupak has moved off into the Docker world.  He hasn't been active *recently*.

**Comment by plribeiro3000** [comment]
There is the point where @fog got splitted so not sure about getting only the main repository files.

**Comment by geemus** [comment]
What does author mean? I'm sure @tokengeek has touched/updated lots, but I doubt (especially post split) that he wholly wrote 24%? If it is just the last person to touch the files, I'm not sure how accurately it reflects the state.

In any event. I think the core fog projects would be fine for the most part, but some of the sub-projects might be more hurt. Those receiving heavy usage seem likely to find new contributors though and somebody from the core team could promote other people up as needed. Perhaps we should expand core-team further though (as there are just 3, of which I'm the only one particularly active presently).

**Comment by plribeiro3000** [comment]
@gavelino I would say that this list is kind of old?

I'm in the community for a while and never seem most of those guys. Maybe we might need another metric other then just files updated?

**Comment by plribeiro3000** [comment]
BTW, thats a nice research. Congratz! :clap:

**Comment by tokengeek** [comment]
My contribution % is inflated due to the way some code is repeated across providers. So various changes touch many files.

As @geemus mentioned above, after the split the number don't quite feel right.

`fog-core` is a critical (sub) part of fog but it's not reflected here. It was extracted by @elight but written by many others. Evan's name doesn't appear even as a wrapper around those changes.

https://github.com/fog/fog-core/graphs/contributors

I guess if your research is based on the _repository_ it might be accurate but less for the _project_

@plribeiro3000 contributions are not showing up either so not sure if there is a missing time factor here. Many contributions, a long time ago may have been an active developer then but things may change so that the impact lessens for some of the people moving on.

Due to work responsibilities I've kind of got a truck parked on my foot at the moment but I don't think that is halting things.

So:

1) No, not really the active developers.
2) No, several names are inactive and project is continuing.
3) No, nothing special except perhaps @geemus leadership/commitment.

I think if Wes ever stopped working on fog, then they'd be trouble. So a TF of 1 almost!

**Comment by fcheung** [comment]
How would changes such as 2e0b7e545a3 affect these metrics? (a rubucop auto correction that touched 3819 files and happened to be committed in by one user).

Personally I know I did a bunch of stuff around the aws bits of fog, but those were extracted into their own sub gem and so don't apply here - I assume the same is true of the other extracted providers.

**Comment by plribeiro3000** [comment]
@gavelino Do you still need this open for tracking purposes or can it be closed?

Thanks!

**Comment by plribeiro3000** [comment]
@gavelino Thanks! Let me know if you need more insights. :+1:

**Comment by gavelino** [comment]
Ok, 

thanks @plribeiro3000.
