### ISSUE TITLE
[vsphere] How to specify a cluster when cloning from template

### ISSUE THREAD

**Issue by pdilung** [fog/fog#3657]
Hello,

How can I specify which cluster will be the VM cloned into?

My usecase is the following:
I have one datacenter `d1` with two clusters `c1d1` and `c2d1`. I want to create a VM called `m1c2d1` in cluster `c2d1` by cloning from a template `t1c1d1` (yes, the template is hosted on a cluster `c1d1`).

Thanks

**Comment by geemus** [comment]
@nirvdrum could you advise? Thanks!

**Comment by nirvdrum** [comment]
Hi @pdilung 

I'm truly sorry for just getting to this.  I think you have two options available, depending on your cluster setup.  One option is to specify the `'dest_folder'` setting, assuming you have a folder associated with the cluster.  The second option is to specify a `'resource_pool'` setting.  If neither of those work for your use case, we'll have to look through the vSphere API docs to see if another option is available because I don't think fog currently supports any other options.

**Comment by pdilung** [comment]
Hi @nirvdrum 

no problem. `'resource_pool'` is no go for our deployments and the `'dest_folder'` did not work, though it's been some time I tried it. Let me test the `'test_folder'` again and report back.

Thanks & BR

Pali

**Comment by estonfer** [comment]
I could be wrong here, but looking in the API docs the VirtualMachineCloneSpec (http://pubs.vmware.com/vsphere-60/topic/com.vmware.wssdk.apiref.doc/vim.vm.CloneSpec.html) as part of the relocation spec requires that a pool be specified.  I believe that all clusters have a default root resource_pool, so I'd think you'd just want to pull and use that  ala myCluster.resource_pools wherein myCluster is your target.

**Comment by plribeiro3000** [comment]
Closing in favor of fog/fog-vsphere#46
