### ISSUE TITLE
ADD: Cloudflare DNS provider?

### ISSUE THREAD

**Issue by eshao** [fog/fog#3681]
Has there been any discussion around adding Cloudflare as a DNS provider similar to Route53? I briefly searched but didn't find anything.

**Comment by geemus** [comment]
Good question, not that I recall (a search would probably be better than my memory at this point anyway). Seems like it would be a nice fit, though we would probably do it as it's own gem/repository that was required, rather than having it be in the main repo (as we are doing with all new stuff and gradually trying to convert old stuff to). Definitely happy to discuss or answer questions if I can. Thanks!

**Comment by plribeiro3000** [comment]
Closing in favor of #3644
