### ISSUE TITLE
Openstack keystone V3 uses deprecated `project_name` instead of `tenant_name` options

### ISSUE THREAD

**Issue by voelzmo** [fog/fog#3687]
**Description**
Using fog 1.34.0, obtaining tokens using the keystone V3 API uses options with different names than the keystone V2 API. 

**Expected behavior**
Switching from V2 to V3 for obtaining tokens for a domain should require changing the URL and adding the new option for specifying the domain - nothing else.

**Actual behavior**
You have to change the options specifying the tenant as well, from `tenant_name` in V2 to `project_name` in V3.

**Analysis**
Obtaining a token in the [V2 API uses the option `tenant_name`]( https://github.com/fog/fog/blob/v1.34.0/lib/fog/openstack/core.rb#L426) to set the tenant for which the token is aquired.
Obtaining a token in the [V3 API uses the option `project_name`](https://github.com/fog/fog/blob/v1.34.0/lib/fog/openstack/core.rb#L460-L469) to set the tenant for which the token is aquired.
The options parsed should probably be `tenant_name` and `tenant_id` repsectively in V3

**Comment by dhague** [comment]
This is by design - tenants do not exist in the V3 API, there are only projects in domains - hence the naming change which reflects the change in the underlying API. This is just one of many cases in which an OpenStack API of vX introduces breaking changes from API v(X-1). To that extent, I disagree with the Expected behaviour described above (although I understand the reasoning behind it).

In summary: a V2 call for tenant_name=X must be translated to a V3 call for project_name=X, domain_name=default.

**Comment by TerryHowe** [comment]
v3 auth should require project name/id and most like a domain of some sort.  It is different.

**Comment by voelzmo** [comment]
@TerryHowe I understand that V3 is different from V2 in that it provides support for domains.

However, it seems that I'm confusing V1 'projects' with V3 'projects' - I wasn't aware that V2 tenants got renamed again to 'projects' in V3.

So I guess that fog won't hide that from me and I have to adapt my calls to fog, changing `tenant_name` to `project_name`. Thanks @dhague for pointing me to that!

**Comment by geemus** [comment]
Thanks for discussing/working through this. Looks solved if I'm not mistaken, so I'll close. Please comment and we can reopen if I'm wrong though. Thanks!
