### ISSUE TITLE
Expected(200) <=> Actual(404 Not Found)

### ISSUE THREAD

**Issue by jamesvanklink** [fog/fog#3828]
I'm working on writing a rspec test using Carrierwave and Fog.  I'm trying to mock Fog and have 
Fog.mock!
Fog.credentials_path = Rails.root.join('config/fog_credentials.yml')
connection = Fog::Storage.new(provider: 'AWS')
connection.directories.create(key: CarrierWave::Uploader::Base.fog_directory)

In a file in my support directory and am including it in my controller test.  However, it is not finding the bucket in the verify_mock_bucket_exists method.  I checked the list of buckets it has and it is an empty list and does not have the one I created above.  I've looked around and everything I'm finding says this should be the solution but it won't work for me and I'm not sure why.

I'm using ruby 2.2.3, fog 1.37.0 and fog-aws 0.8.1.

Thanks

**Comment by geemus** [comment]
That should work, I think. It does use the credentials to segregate mock data though, so be sure the controllers and/or tests are using the same credentials as the directory create there or you may have issues. Otherwise I would expect that to work though. Let me know if you still come up short and I can certainly help troubleshoot further. Thanks!

**Comment by jamesvanklink** [comment]
That indeed was the issue.  Thanks for the help.
