### ISSUE TITLE
Add Azure entry in Fog's provider list

### ISSUE THREAD

**Issue by abbas-sheikh-confiz** [fog/fog#3904]
Hi @geemus ,

Please add entry for Azure(resource manager) support on list of providers page
http://fog.io/about/provider_documentation.html

Following is the information
Documentation Link:
https://github.com/fog/fog-azure-rm

Examples Link:
https://github.com/fog/fog-azure-rm/tree/master/test/integration

Kindly, let us know if you need more information.

Thanks,

**Comment by plribeiro3000** [comment]
Hello @abbas-sheikh-confiz. Before we add it as a supported provider we need to include it as a dependency on `fog`.
Then you should be able to add the documentation support yourself by sending a PR to https://github.com/fog/fog.github.com.

And before adding it as a dependency to `fog` some concerns need to be addressed.
Like, why do you have [this begin rescue](https://github.com/fog/fog-azure-rm/blob/master/lib/fog/azurerm.rb#L18-L38) instead of use the fog DSL for services?

Can you make sure the repo is following the steps [here](https://github.com/fog/fog/wiki/Create-New-Provider-from-Scratch)?

Thanks!

**Comment by AbelHu** [comment]
@abbas-sheikh-confiz : It is so exciting to know that Azure will be as a provider in Fog. Could you share your schedule for this? When will you refine fog-azure-rm as @plribeiro3000 said?

**Comment by abbas-sheikh-confiz** [comment]
Hi @AbelHu,

We will add this support soon.

Regards,

**Comment by plribeiro3000** [comment]
I will close this as of now. When `fog-azure` get ready we can reopen this.

**Comment by bilal-naeem-confiz** [comment]
fog-azure-rm can not support ruby versions < 2.0 because the Azure SDK that we are using no longer supports ruby versions below 2.0 as mentioned here [Azure SDK README](https://github.com/Azure/azure-sdk-for-ruby/blob/master/README.md)

**Comment by abbas-sheikh-confiz** [comment]
We are in limbo state, until Fog is supporting 1.9. We can not add fog-azure-rm support.

**Comment by AbelHu** [comment]
@abbas-sheikh-confiz In Fog [README](https://github.com/fog/fog/blob/master/README.md), Fog requires Ruby `2.0.0` or later. So I think it should not be a problem, is it?

------------------------------------------------
## Ruby version

Fog requires Ruby `2.0.0` or later.

Ruby `1.8` and `1.9` support was dropped in `fog-v2.0.0` as a backwards incompatible
change. Please use the later fog `1.x` versions if you require `1.8.7` or `1.9.x` support.

**Comment by plribeiro3000** [comment]
@AbelHu Actually thats a missdocumentation. 😅 
If you take a look a the gemspec [here](https://github.com/fog/fog/blob/master/fog.gemspec#L105-L114) you will see it has support for ruby `1.9.3`.
What it seems to be is that we can't add support for `fog-azure` within `fog` for now.
Long story short we are still developing on `1.x` branch because there is mane use cases of `fog` that require so. =s
We can have `fog-azurerm` as a standalone gem for now. Isn't that enough for now?

**Comment by NingKuang** [comment]
Hi, @plribeiro3000 @abbas-sheikh-confiz 
Thanks for the help! 
We did some research, using standalone gem will require a lot changes on Cloud Foundry side.
I was wondering whether you guys are planning to build a new branch of  fog-azure-rm to support 1.x?
What is the timeline ? 
Thanks!

**Comment by plribeiro3000** [comment]
@NingKuang Always glad to help.
Unfortunately i don't have the spare time to get hands on this now. Maybe if the guys that did all the work on `fog-azure-rm` can do it.
The main issue is that we will have to drop the gem that supports all the interface with azure and start doing the requests from within `fog-azure-rm` which is a little bit of effort.

@NingKuang Fog Azure is not ready yet and might change a lot until it is officially supported. Keep in mind you might have breakages until it is done.

@abbas-sheikh-confiz Do you think is feasible to start doing the http calls manually? (That would also be compliant with `fog` standards).

**Comment by NingKuang** [comment]
Thanks @abbas-sheikh-confiz @plribeiro3000 !
Do you mean calling http-call manually inside Cloud Foundry?
For Cloud Foundry, the fog call to utilize a specific cloud provider's storage is through standard fog API interface that works for all platforms. Anything not using standard fog interface will require modifying the common Cloud Foundry code, detecting the specific platform, and replace every fog call with Azure specific interfacesl This is very hard to maintain and ensure quality. 
The ideal solution is still to support fog as an official provider. Any idea how long this will take? Thanks!

**Comment by plribeiro3000** [comment]
Not sure i got what you mean. 😬 

My thought is that right now depends on a [bunch of gems](https://github.com/fog/fog-azure-rm/blob/master/fog-azure-rm.gemspec#L27-L32) to do the interface with `Azure`.

This is not something we intend to have since it just increase the dependency tree for users that have `fog` in their Gemfile.

The solution is to remove such client libraries and do all the interface with `Azure` with plain http calls. This also release the constraint we have with ruby `> 2.0` right now.

As for Cloud Foundry i'm afraid i don't have enough knowledge/information to help out. Does it run on top of `Azure`?

**Comment by NingKuang** [comment]
@plribeiro3000  Yes Cloud Foundry runs on Azure.
OK, you mean http call directly to Azure for fog-azure-rm ?  Good question to our confiz friends  :)    @abbas-sheikh-confiz  ?

**Comment by geemus** [comment]
@NingKuang yeah, the interface to fog-users would be the same. The question was more about internals of what the requests actually do (raw-http vs a gem). Most fog stuff does raw, which takes a bit more work, but also limits external dependencies.
