### ISSUE TITLE
Fog 2.0 has fog-core dependency of ~> 1.45 and fog-json ~> 2.0

### ISSUE THREAD

**Issue by tokengeek** [fog/fog#3999]
When `fog-2.0.0` was released, I can't see a bump in the gemspec for `fog-core` so it is pessimistically tracking fog-core 1.x at the moment.

The Travis tests are failing with the `Gemfile-edge` because it can no longer resolve the dependencies because `fog-json` *did* get a bump:

```
Resolving dependencies...
Bundler could not find compatible versions for gem "fog-core":
  In Gemfile-edge:
    fog was resolved to 2.0.0, which depends on
      fog-core (~> 1.45)
    fog was resolved to 2.0.0, which depends on
      fog-json was resolved to 1.1.0, which depends on
        fog-core (~> 2.0)
```
https://travis-ci.org/fog/fog/jobs/395113453#L471

It's a simple enough fix but I just wanted to clarify if I missed some discussion. We can either go `">= 1.45", "< 3.0"` or bump to `~> 2.0` as well OR clean up `fog-json` to not declare a dependency version.

I'm just not sure if this was an oversight or it was decided to leave the main version open for a while.

cc @geemus, @plribeiro3000

**Comment by plribeiro3000** [comment]
Hmmm. I believe it was a good catch. At least for me it was complete lack of attention.

For the solution i think we should do both unless `fog-json` has a hard dependency for some reason (which i don't think it does).

Since `fog-json` is a second level dependency regarding extracted providers, i think we should release the version and fix the version in `fog`.

Just a random question, Do we need `fog-json` to depend on `fog-core` at all? I mean, everyone depending on `fog-json` depend on `fog-core`. Maybe we can avoid this dependency?

**Comment by tokengeek** [comment]
It's not that random a question. It's actually a good point. I've just tested and the dependency is for `Fog::Errors::Error`

https://github.com/fog/fog-json/blob/6fe9ec70201d784498ff36bd51ff44a6affd2451/lib/fog/json.rb#L13-L14

So dropping the dependency would change the error handling since rescuing `Fog::Errors::Error` would not catch encoding errors.

I think removing the dependency altogether is probably the best since the module namespace should be fairly stable.

Done that with https://github.com/fog/fog-json/pull/15

**Comment by plribeiro3000** [comment]
Coolio!

**Comment by geemus** [comment]
Thanks!
