### ISSUE TITLE
OSX, Monterey `const_defined?': uninitialized constant Fog::Rackspace::CDN (NameError)

### ISSUE THREAD

**Issue by realpagerajesh** [fog/fog#4076]
Hi I have upgraded my OS from BigSur go Montery recently. I am stuck with the issue below for stating my rails application.
Kindly please help 

`/Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/fog-core-2.3.0/lib/fog/core/provider.rb:48:in `const_defined?': uninitialized constant Fog::Rackspace::CDN (NameError)
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/fog-core-2.3.0/lib/fog/core/provider.rb:48:in `service_klass'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/fog-core-2.3.0/lib/fog/core/provider.rb:37:in `service'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/fog-rackspace-0.1.6/lib/fog/rackspace.rb:53:in `<module:Rackspace>'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/fog-rackspace-0.1.6/lib/fog/rackspace.rb:28:in `<module:Fog>'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/fog-rackspace-0.1.6/lib/fog/rackspace.rb:10:in `<top (required)>'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/fog-2.2.0/lib/fog.rb:42:in `<top (required)>'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/bundler/gems/carrierwave-ff89d6e1c055/lib/carrierwave/storage.rb:5:in `<top (required)>'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/bundler/gems/carrierwave-ff89d6e1c055/lib/carrierwave.rb:78:in `<top (required)>'
	from /Users/rajesh.banoth/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:81:in `require'
	from /Users/rajesh.banoth/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:81:in `block (2 levels) in require'
	from /Users/rajesh.banoth/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:76:in `each'
	from /Users/rajesh.banoth/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:76:in `block in require'
	from /Users/rajesh.banoth/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:65:in `each'
	from /Users/rajesh.banoth/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler/runtime.rb:65:in `require'
	from /Users/rajesh.banoth/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/bundler.rb:114:in `require'
	from /Users/rajesh.banoth/code/pwm/config/application.rb:7:in `<top (required)>'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:78:in `require'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:78:in `block in server'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/railties-4.2.11.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/gems/railties-4.2.11.3/lib/rails/commands.rb:17:in `<top (required)>'
	from bin/rails:4:in `require'
	from bin/rails:4:in `<main>'
`

**Comment by tokengeek** [comment]
From the stacktrace, it looks like you are using `carrierwave` rather than fog directly. Is that correct?

Are you using Rackspace for file uploads?

It looks like you are using a specific SHA of `carrierwave` (ff89d6e1c055) or at least a non-release version. I can't find a matching SHA in the carrierwave repo so that is the biggest question at the moment.

```
from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/bundler/gems/carrierwave-ff89d6e1c055/lib/carrierwave/storage.rb:5:in <top (required)>' from /Users/rajesh.banoth/.rvm/gems/ruby-2.3.1/bundler/gems/carrierwave-ff89d6e1c055/lib/carrierwave.rb:78:in <top (required)>'
```

The error looks like a dependency problem in your gems rather than the switch in OS X versions itself. I'm not sure if the Ruby version has changed causing one of the gems to change unexpectedly or if a `bundle install` has just pulled down much newer versions of the gems but your carrierwave version isn't compatible.

The `Fog::Rackspace::CDN` class is the deprecated/older format of the provider/service and the code should be warning you about deprecation rather than failing to load.

Have you run `bundler update carrierwave fog` to make sure you have the latest versions?

If you are not using `fog` directly it may be a carrierwave issue since you should just need to require `carrierwave` and `fog-rackspace` and the latest versions should work together.

Sorry I can't be much more help.
