### ISSUE TITLE
DELL Powerscale S3 Support

### ISSUE THREAD

**Issue by draufer** [fog/fog#4117]
Hi,

we are using a DELL Powerscale Storage Solution (NAS). It features S3 functionality.
We are running Gitlab on K8s and are trying to upload Artifacts to the Powersclae S3 Service - which fails. Some simple files like job-logs are stored on the file system - so generally S3 seems to be working.

We seem to have Problems with the Multipart-Upload:
```
Uploading artifacts...
test.txt: found 1 matching artifact files and directories 
WARNING: Uploading artifacts as "archive" to coordinator... POST https://git.xxx.de/api/v4/jobs/34/artifacts: 400 Bad Request (Expected(200) <=> Actual(501 Not Implemented)
excon.error.response
  :body              => "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>NotImplemented</Code><Message>Transfer encoding is not implemented.</Message><Resource></Resource><RequestId>566406963</RequestId></Error>"
  :cookies           => [
  ]
  :headers           => {
    "Connection"       => "close"
    "Content-Length"   => "189"
    "x-amz-request-id" => "566406963"
  }
  :host              => "xxx.de"
  :local_address     => "10.233.66.134"
  :local_port        => 34004
  :method            => "PUT"
  :omit_default_port => false
  :path              => "/gitlab-artifacts-storage/6b/86/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/2024_07_29/34/129/metadata.gz"
  :port              => 9021
  :query             => nil
  :reason_phrase     => "Not Implemented"
  :remote_ip         => "10.15.129.40"
  :scheme            => "https"
  :status            => 501
  :status_line       => "HTTP/1.1 501 Not Implemented\r\n"
)  id=34 responseStatus=400 Bad Request status=400 token=glcbt-64
WARNING: Retrying...                                context=artifacts-uploader error=invalid argument
WARNING: Uploading artifacts as "archive" to coordinator... POST https://git.xxx.de/api/v4/jobs/34/artifacts: 400 Bad Request (SSL_read: unexpected eof while reading (OpenSSL::SSL::SSLError))  id=34 responseStatus=400 Bad Request status=400 token=glcbt-64
```

How can I assist to add the Powerscale to the supported S3-Providers?

Best regards,
Dirk

**Comment by geemus** [comment]
@draufer thanks for reaching out with the detailed report, I'd be happy to try and help you through it. That being said, it's not an area I have particular experience with, so I may need to go back and forth with you a bit to gather more context.

Your analysis that it's likely multipart at issue, instead of S3 usage in general, sounds likely.

Are these calls you are making directly that are failing, or are they things happening somewhere deeper in gitlab or other code that you don't directly control? If you could share context around the particulars of how this is being called that would be helpful. Also if you could share in broad strokes the kind of files we are talking about that are failing (mostly, how big are they).

One other small note, this is likely more of an issue with fog-aws than the core fog stuff, fwiw. But it's fine to discuss here to start.

**Comment by draufer** [comment]
Hi @geemus,

the calls that are made are a result of executing a CI/CD pipeline in gitlab that creates a zip file artifact with one txt file and about 5-20 characters of ASCII text. So no - they are no direct calls.

The gitlab-ci.yml file looks like this:
```
variables:
  APP_NAME: "demo"
 
stages:
  - build
 
build_job:
  stage: build
  script:
    - echo "Building $APP_NAME"
  artifacts:
    paths:
      - test.txt
```
The content of the file test.txt is:
```
test14
```
I did the testing by committing a change to the file - triggering the pipeline.

The S3-related gitlab configuration is the following:

From the helm values.yml (we are using the [consolidated form](https://docs.gitlab.com/ee/administration/object_storage.html#configure-a-single-storage-connection-for-all-object-types-consolidated-form)):
```
global:
  minio:
    enabled: false
  appConfig:
    object_store:
      enabled: true
      storage_options: {}
      connection:
        secret: gitlab-rails-storage
    lfs:
      enabled: true
      bucket: gitlab-lfs-storage
      connection:
    artifacts:
      enabled: true
      bucket: gitlab-artifacts-storage
      connection:
    uploads:
      enabled: true
      bucket: gitlab-uploads-storage
      connection:
    packages:
      enabled: true
      bucket: gitlab-packages-storage
      connection:
    externalDiffs:
      enabled: true
      bucket: gitlab-externaldiffs-storage
      connection:
    terraformState:
      enabled: true
      bucket: gitlab-terraform-state
      connection:
    dependencyProxy:
      enabled: true
      bucket: gitlab-dependencyproxy-storage
      connection:
    ciSecureFiles:
      enabled: true
      bucket: gitlab-ci-secure-files
      connection:
```

The secret gitlab-rails-storage is:
```
provider: AWS
region: xxx:9021
aws_access_key_id: yyy
aws_secret_access_key: zzz
aws_signature_version: 4
enable_signature_v4_streaming: true
endpoint: "https://xxx:9021"
path_style: true
```

Regarding the DELL Powerscale:
We run version 9.4.0.13
We found this document regarding Multipart Upload: https://infohub.delltechnologies.com/en-us/l/dell-powerscale-onefs-s3-api-guide/createmultipartupload/

I just ran a job and I see these files on the storage:
```
./git-it-gitlab-artifacts-storage/6b/86/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/2024_07_30/35
./git-it-gitlab-artifacts-storage/6b/86/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/2024_07_30/35/.isi_s3_dir
./git-it-gitlab-artifacts-storage/6b/86/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/2024_07_30/35/141
./git-it-gitlab-artifacts-storage/6b/86/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/2024_07_30/35/141/.isi_s3_dir
./git-it-gitlab-artifacts-storage/6b/86/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/2024_07_30/35/141/job.log
```

This is the corresponding gitlab CI/CD job log:
```
Uploading artifacts...
test.txt: found 1 matching artifact files and directories 
WARNING: Uploading artifacts as "archive" to coordinator... POST https://xxx/api/v4/jobs/35/artifacts: 400 Bad Request (SSL_read: unexpected eof while reading (OpenSSL::SSL::SSLError))  id=35 responseStatus=400 Bad Request status=400 token=glcbt-64
WARNING: Retrying...                                context=artifacts-uploader error=invalid argument
WARNING: Uploading artifacts as "archive" to coordinator... POST https://xxx/api/v4/jobs/35/artifacts: 400 Bad Request (SSL_read: unexpected eof while reading (OpenSSL::SSL::SSLError))  id=35 responseStatus=400 Bad Request status=400 token=glcbt-64
WARNING: Retrying...                                context=artifacts-uploader error=invalid argument
WARNING: Uploading artifacts as "archive" to coordinator... POST https://xxx/api/v4/jobs/35/artifacts: 400 Bad Request (Expected(200) <=> Actual(501 Not Implemented)
excon.error.response
  :body              => "<?xml version=\"1.0\" encoding=\"UTF-8\"?><Error><Code>NotImplemented</Code><Message>Transfer encoding is not implemented.</Message><Resource></Resource><RequestId>566409118</RequestId></Error>"
  :cookies           => [
  ]
  :headers           => {
    "Connection"       => "close"
    "Content-Length"   => "189"
    "x-amz-request-id" => "566409118"
  }
  :host              => "xxx"
  :local_address     => "10.233.66.134"
  :local_port        => 56518
  :method            => "PUT"
  :omit_default_port => false
  :path              => "/gitlab-artifacts-storage/6b/86/6b86b273ff34fce19d6b804eff5a3f5747ada4eaa22f1d49c01e52ddb7875b4b/2024_07_30/35/140/metadata.gz"
  :port              => 9021
  :query             => nil
  :reason_phrase     => "Not Implemented"
  :remote_ip         => "10.15.129.40"
  :scheme            => "https"
  :status            => 501
  :status_line       => "HTTP/1.1 501 Not Implemented\r\n"
)  id=35 responseStatus=400 Bad Request status=400 token=glcbt-64
FATAL: invalid argument                            
Cleaning up project directory and file based variables
00:01
ERROR: Job failed: command terminated with exit code 1
```

I really appreciate your help @geemus!
Let me know what I can do to assist...

Best regards
Dirk

**Comment by geemus** [comment]
Ok, first off thanks again for the details, that helped me narrow it down to what I needed to know (through a few layers of indirection).

It looks like gitlab is using carrierwave for file management, which in turn uses fog. And it looks like the issue is that fog tries to be smart about file uploads based on how big they are. So if they are small enough it just puts them all in one go, but if they are big it tries to do multipart uploading. Furthermore, to avoid overwhelming system memory it tries to do the multipart upload with chunks via chunked encoding. Unfortunately it looks like the multipart uploading for the Dell implementation does not support chunked.

It seems that others have run into this with other providers though, as I can see there appears to be some related pressure-relief code in fog itself. In particular, it looks like if you set `:max_put_chunk_size` in the rails storage config/credentials to a non-positive value (`0` is probably a decent choice), it will bypass the multipart uploading and upload it all as a single file. See: https://github.com/fog/fog-aws/blob/master/lib/fog/aws/storage.rb#L140

At least that is the simplest/fastest way to solve this. With the side effect being that the whole file will get loaded into memory while making the request. This may actually be more performant as long as the file sizes are small enough to not overwhelm system memory, but for really big files it could be problematic.

I'm hoping this will get you unstuck and running the way you want, but do let me know if you have further questions or this doesn't resolve things for you.

**Comment by draufer** [comment]
Hi @geemus,

Disabling the chunked transfer did work for now.

I used a gitlab-rails-storage secret as following:
```
provider: AWS
region: "xxx:9021"
aws_access_key_id: yyy
aws_secret_access_key: zzz
aws_signature_version: 4
enable_signature_v4_streaming: false
endpoint: "https://xxx:9021"
path_style: true
max_put_chunk_size: 0
```

Thank you very much for your assistance @geemus!

**Comment by geemus** [comment]
Glad to hear that fixed it for you, thanks for sharing the config, may be quite helpful for somebody else some day.
